import Navbar from '@/components/netflix/Navbar'
import { AuthContextProvider } from '@/context/AuthContext'
import '@/styles/globals.css'
import Head from 'next/head'

export default function App({ Component, pageProps }) {
  return (
  <>
  <AuthContextProvider>
  <Head>
        <title>NETFLIX CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
  </Head>
  <Navbar/>
  <Component {...pageProps} />
  </AuthContextProvider>
  </>
  )
}
