import React from 'react'

import Row from '@/components/netflix/Row'
import Main from '@/components/netflix/Main'



import requests from '@/Requests'
import Head from 'next/head'



const NetflixPage = () => {
    return (
        <>
      <Head>
        <title>NETFLIX CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <Main />
       <Row rowID='1' title='Now Playing' fetchURL={requests.requestHorror} />
       <Row rowID='2' title='UpComing' fetchURL={requests.requestUpcoming} />
       <Row rowID='3' title='Popular' fetchURL={requests.requestPopular} />
       <Row rowID='4' title='Trending' fetchURL={requests.requestTrending} />
       <Row rowID='5' title='Top Rated' fetchURL={requests.requestTopRated} />
       
      </main>
    </>
    )
}

export default NetflixPage